/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.register;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sergi
 */
public class RegisterPanel extends javax.swing.JPanel {
    private RegisterPanelController myController;
    private final int MAX_ICONS = 5;
    private ImageIcon[] icons = new ImageIcon[MAX_ICONS];
    /**
     * Creates new form RegisterPanel
     */
    private RegisterPanel() {
        initComponents();
        prepareCombobox();
    }
    public RegisterPanel(RegisterPanelController controller){
        this();
        this.myController = controller;
    }
    
    private void prepareCombobox(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (int i = 1; i <= MAX_ICONS; i++) {
            icons[i-1] = new javax.swing.ImageIcon(getClass().getResource("/images/user/user_"+i+".png"));
            model.addElement("Ícone "+i);
        }
        combouserIcons.setModel(model);
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        combouserIcons = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPassWord = new javax.swing.JPasswordField();
        txtDateBirth = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnreturn = new javax.swing.JButton();
        lbIcon = new javax.swing.JLabel();
        btnRegister1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 400, 0};
        layout.rowHeights = new int[] {0, 100, 0};
        setLayout(layout);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/400X300_logo_uno.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jLabel1, gridBagConstraints);

        jPanel1.setOpaque(false);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combouserIcons.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combouserIconsItemStateChanged(evt);
            }
        });
        jPanel2.add(combouserIcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, 20));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Usuário");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 70, 230, -1));

        txtLogin.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jPanel2.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 230, -1));

        txtName.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Nome");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 230, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Senha");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 230, -1));
        jPanel2.add(txtPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, -1));

        txtDateBirth.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jPanel2.add(txtDateBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 230, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Data de nascimento");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 230, -1));

        btnreturn.setBackground(new java.awt.Color(235, 26, 34));
        btnreturn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnreturn.setForeground(new java.awt.Color(255, 255, 255));
        btnreturn.setText("Voltar");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        jPanel2.add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 230, 40));

        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user/user_1.png"))); // NOI18N
        jPanel2.add(lbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        btnRegister1.setBackground(new java.awt.Color(0, 149, 203));
        btnRegister1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnRegister1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister1.setText("Cadastrar");
        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/250X300_background.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 350));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.2;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        // TODO add your handling code here:
        myController.returnPage();
    }//GEN-LAST:event_btnreturnActionPerformed

    private void combouserIconsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combouserIconsItemStateChanged
        // TODO add your handling code here:
        lbIcon.setIcon(icons[combouserIcons.getSelectedIndex()]);
    }//GEN-LAST:event_combouserIconsItemStateChanged

    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed
        // TODO add your handling code here:
        String srcIcon = "user_"+(combouserIcons.getSelectedIndex()+1)+".png";
        myController.registerUser(
                txtLogin.getText(),
                txtName.getText(),
                txtDateBirth.getText(),
                String.valueOf(txtPassWord.getPassword()),
                srcIcon
        );
    }//GEN-LAST:event_btnRegister1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister1;
    private javax.swing.JButton btnreturn;
    private javax.swing.JComboBox<String> combouserIcons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JTextField txtDateBirth;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassWord;
    // End of variables declaration//GEN-END:variables

    public void showAlertDialog(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
}
