/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.util;

import view.notification.NotificationType;
import view.notification.NotificationEventsInterface;

/**
 *
 * @author sergi
 */
public class Notification extends javax.swing.JPanel {
    private NotificationEventsInterface notifyInterface;
    /**
     * Creates new form Notify
     */
    public Notification(NotificationType notificationType,String message) {
        initComponents();
        defineType(notificationType);
        labelText.setText(message);
        this.notifyInterface= notifyInterface;
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelText = new javax.swing.JLabel();
        labelBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(499, 31));
        setMinimumSize(new java.awt.Dimension(499, 31));
        setPreferredSize(new java.awt.Dimension(499, 31));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 10, -1));

        labelText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        labelText.setForeground(new java.awt.Color(255, 255, 255));
        labelText.setText("Teste");
        add(labelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, -1));

        labelBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notify_warning.png"))); // NOI18N
        add(labelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
       notifyInterface.onCloseNotification();
    }//GEN-LAST:event_jLabel1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelText;
    // End of variables declaration//GEN-END:variables

    private void defineType(NotificationType notificationType) {
        switch(notificationType){
            case INFO:
                labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notify_info.png")));
                break;
            case WARNING:
                labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notify_warning.png")));
                break;
            case DANGER:
                labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notify_danger.png")));    
                break;
        }
    }

    public void setInterface(NotificationEventsInterface notificationInterface) {
        this.notifyInterface =notificationInterface;
    }

 
}
