/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.login;



/**
 *
 * @author sergi
 */
public class LoginPanel extends javax.swing.JPanel {
    private LoginController mController;
    /**
     * Creates new form LoginPanel
     */
    private LoginPanel() {
        initComponents();
    }
    public LoginPanel(LoginController controller){
        this();
        this.mController = controller;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        btnRanking1 = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        passWord = new javax.swing.JPasswordField();
        backgroundLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setOpaque(false);
        panelLogin.setPreferredSize(new java.awt.Dimension(250, 250));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRanking1.setBackground(new java.awt.Color(0, 149, 203));
        btnRanking1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnRanking1.setForeground(new java.awt.Color(51, 51, 51));
        btnRanking1.setText("Visualizar ranking");
        panelLogin.add(btnRanking1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 200, -1));

        btnLogin.setBackground(new java.awt.Color(122, 213, 75));
        btnLogin.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, -1));

        btnRegister.setBackground(new java.awt.Color(0, 149, 203));
        btnRegister.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Cadastrar");
        panelLogin.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Senha");
        panelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Usuário");
        panelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, -1));

        txtLogin.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        txtLogin.setText("sdteotonio");
        panelLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, -1));
        panelLogin.add(passWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, -1));

        backgroundLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_login.png"))); // NOI18N
        panelLogin.add(backgroundLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 240, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/256x230_logo_uno.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    // TODO add your handling code here:
        this.setVisible(false);
        mController.onBtnLoginClicked();
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRanking1;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
