/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.menu;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sergi
 */
public class MenuPanel extends javax.swing.JPanel {
    private MenuPanelController controller;
    /**
     * Creates new form MenuPanel
     */
    private MenuPanel() {
        initComponents();
        enableButtons(true);
    }

    public MenuPanel(MenuPanelController myController) {
        this();
        this.controller = myController;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_panel = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_panel.setOpaque(false);

        btnStart.setBackground(new java.awt.Color(122, 213, 75));
        btnStart.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnStart.setForeground(new java.awt.Color(51, 51, 51));
        btnStart.setText("Iniciar jogo");
        btnStart.setBorderPainted(false);

        btnContinue.setBackground(new java.awt.Color(247, 217, 37));
        btnContinue.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnContinue.setForeground(new java.awt.Color(51, 51, 51));
        btnContinue.setText("Continuar jogo");

        btnRanking.setBackground(new java.awt.Color(0, 149, 203));
        btnRanking.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnRanking.setForeground(new java.awt.Color(51, 51, 51));
        btnRanking.setText("Visualizar ranking");

        btnOut.setBackground(new java.awt.Color(235, 26, 34));
        btnOut.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnOut.setForeground(new java.awt.Color(51, 51, 51));
        btnOut.setText("Sair do jogo");
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout button_panelLayout = new javax.swing.GroupLayout(button_panel);
        button_panel.setLayout(button_panelLayout);
        button_panelLayout.setHorizontalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        button_panelLayout.setVerticalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart)
                .addGap(21, 21, 21)
                .addComponent(btnContinue)
                .addGap(21, 21, 21)
                .addComponent(btnRanking)
                .addGap(21, 21, 21)
                .addComponent(btnOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(button_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 220, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo_Uno_600x500.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
    
        controller.exitApp();
    }//GEN-LAST:event_btnOutActionPerformed

    public boolean confirmExit(){
        return JOptionPane.showConfirmDialog(this, "Deseja sair?","Sair", JOptionPane.OK_CANCEL_OPTION)==2?true:false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel button_panel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void enableButtons(boolean b) {
        btnContinue.setEnabled(b);
        btnOut.setEnabled(b);
        btnStart.setEnabled(b);
        btnRanking.setEnabled(b);
    }
}
