/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.menu;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sergi
 */
public class MenuPanel extends javax.swing.JPanel {
    private MenuPanelController controller;
    /**
     * Creates new form MenuPanel
     */
    private MenuPanel() {
        initComponents();
        tutoPanel.setVisible(false);

    }

    public MenuPanel(MenuPanelController myController) {
        this();
        this.controller = myController;
        
    }
    public void showTutorial(boolean  show){
        tutoPanel.setVisible(show);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tutoPanel = new javax.swing.JPanel();
        btnExitTutorial = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button_panel = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnOut = new javax.swing.JButton();
        iconBack = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tutoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExitTutorial.setText("X");
        btnExitTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitTutorialActionPerformed(evt);
            }
        });
        tutoPanel.add(btnExitTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ninja_64.png"))); // NOI18N

        jLabel3.setText("Cococococococ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 234, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tutoPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, -1, 320));

        add(tutoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 480, 440));

        button_panel.setOpaque(false);

        btnStart.setBackground(new java.awt.Color(122, 213, 75));
        btnStart.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnStart.setForeground(new java.awt.Color(51, 51, 51));
        btnStart.setText("Iniciar jogo");
        btnStart.setBorderPainted(false);

        btnContinue.setBackground(new java.awt.Color(247, 217, 37));
        btnContinue.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnContinue.setForeground(new java.awt.Color(51, 51, 51));
        btnContinue.setText("Continuar jogo");

        btnRanking.setBackground(new java.awt.Color(0, 149, 203));
        btnRanking.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnRanking.setForeground(new java.awt.Color(51, 51, 51));
        btnRanking.setText("Visualizar ranking");

        btnOut.setBackground(new java.awt.Color(235, 26, 34));
        btnOut.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnOut.setForeground(new java.awt.Color(51, 51, 51));
        btnOut.setText("Sair do jogo");
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout button_panelLayout = new javax.swing.GroupLayout(button_panel);
        button_panel.setLayout(button_panelLayout);
        button_panelLayout.setHorizontalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        button_panelLayout.setVerticalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart)
                .addGap(21, 21, 21)
                .addComponent(btnContinue)
                .addGap(21, 21, 21)
                .addComponent(btnRanking)
                .addGap(21, 21, 21)
                .addComponent(btnOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(button_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 220, 200));

        iconBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo_Uno_600x500.png"))); // NOI18N
        add(iconBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
    
        controller.exitApp();
    }//GEN-LAST:event_btnOutActionPerformed

    private void btnExitTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitTutorialActionPerformed
        // TODO add your handling code here:
        controller.exitTutorial();
    }//GEN-LAST:event_btnExitTutorialActionPerformed

    public boolean confirmExit(){
        return JOptionPane.showConfirmDialog(this, "Deseja sair?","Sair", JOptionPane.OK_CANCEL_OPTION)==2?true:false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnExitTutorial;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel button_panel;
    private javax.swing.JLabel iconBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel tutoPanel;
    // End of variables declaration//GEN-END:variables

    public void enableComponents(boolean b) {
        btnContinue.setEnabled(b);
        btnOut.setEnabled(b);
        btnStart.setEnabled(b);
        btnRanking.setEnabled(b);
        iconBack.setEnabled(b);
    }
}
